### PR TITLE
Da/surg

### PR DESCRIPTION
**Pull request by tadad**
**Problem**:
you need to use pokes to coerce your gall agent state

**Solution**:
directly edit the state

**Notes**:
- I also changed all the sys/ files for pyro to symlinks
- small fix to %pyre's on-load to resubscribe
- reorganized pyro's lib files now that we aren't in uqbar-core

### CODE REVIEW

**Comment by hosted-fornet** [comment]
This looks really nice, I'll try to review and test today. I am wondering if there is a way we can make it easy to get current gall state vases out of pyro. E.g., with the current system it looks like I can change the state to a vase, but it would be really nice to be able to work from a template, like current state, otherwise I'll have to compose the entire state by hand. I imagine oftentimes I would just want to tweak a single field in the state, and so having to compose the entire state would be annoying -- much easier if I could scry out current state, modify one piece, then plug it back in.

I guess we just need typed pyro scries, and then we can use the existing /i scry system to scry /dbug/state, at least for agents wrapped with lib/dbug.

**Comment by hosted-fornet** [comment]
Note it is especially important to be able to scry out typed stuff when we are dealing with vases, because `;;  vase`ing on most vases you will see in the wild takes a very long time.

**Comment by tadad** [comment]
yeah I think we can get to improving this as we play around with it more

**Review by hosted-fornet — COMMENTED** [review]
Just got to trying this out. Works great. Nice work!

I reiterate the need for typed scrying so we can scry out vases -- most apps have state that we are not going to want to write out by hand, and so need to be able to scry out current state, alter it, then give it back.

**Pull request merged**
